version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
      - ./.docker/postgres:/data/postgres
    ports:
      - "5433:5433"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
